[package]
name = "krpsim_check"
version = "0.1.0"
authors = ["lsimon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
